language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  # pypandoc is needed only for submitting package to pypi
  - sed '/pypandoc/d' -i requirements.txt
  - pip install -U -r requirements.txt
  - ./setup.py install
script:
  - py.test --cov=ssh_ldap_pubkey --cov-report term -vv
  - pycodestyle
